CREATE TABLE IF NOT EXISTS topics (
    id   INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sources (
    id   INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    url  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS styles (
    id     INTEGER PRIMARY KEY AUTOINCREMENT,
    name   TEXT NOT NULL,
    prompt TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS drafts (
    id       INTEGER PRIMARY KEY AUTOINCREMENT,
    title    TEXT NOT NULL,
    content  TEXT NOT NULL DEFAULT '',
    topic_id INTEGER NOT NULL REFERENCES topics(id) ON DELETE RESTRICT,
    style_id INTEGER NOT NULL REFERENCES styles(id) ON DELETE RESTRICT,
    status   TEXT NOT NULL DEFAULT 'draft'
);
